services:
  db:
    image: postgres:latest
    container_name: jj-db
    restart: always
    environment:
      - POSTGRES_DB=jjdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - jj_db_data:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    networks:
      jj-network:
        ipv4_address: 172.28.5.2
    ports:
      - 5434:5432

  jj:
    build:
      context: .
    environment:
      PORT: 8080
      DB_NAME: jjdb
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432
      SECRET_KEY: 7788
    networks:
      jj-network:
        ipv4_address: 172.28.5.3
    depends_on:
      - db
    ports:
      - '8080:8080'

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: jj-pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 8888:80
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      jj-network:
        ipv4_address: 172.28.5.4

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      jj-network:
        ipv4_address: 172.28.5.5

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      jj-network:
        ipv4_address: 172.28.5.6

  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter_service
    ports:
      - 9100:9100
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    networks:
      jj-network:
        ipv4_address: 172.28.5.7


networks:
  jj-network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.1.1

volumes:
  jj_db_data:
  pgadmin-data:
  prometheus-data:
  grafana-data: