services:
  db:
    image: postgres:latest
    container_name: jj-db
    restart: always
    environment:
      - POSTGRES_DB=jjdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./dbdata:/docker-entrypoint-initdb.d
    networks:
      jj-network:
        ipv4_address: 172.28.5.2
    ports:
      - 5434:5432

  jj:
    build:
      context: .
    environment:
      PORT: 8080
      DB_NAME: jjdb
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432
      SECRET_KEY: 7788
    networks:
      jj-network:
        ipv4_address: 172.28.5.3
    depends_on:
      - db
    ports:
      - '8080:8080'

networks:
  jj-network:
    ipam:
      config:
        - subnet: 172.28.0.0/16